### PR TITLE
Stratification groups via data migration

### PR DESCRIPTION
**Pull request by epatters**
This may not get used for the demo, but I wanted to show how it works. I wasn't sure where to put the notebook, so feel free to move it somewhere else.

### CODE REVIEW

**Comment by jpfairbanks** [comment]
This is pretty cool @epatters, can you explain the arg1, arg2 syntax in the migration macro?

```julia
group_migration = @migration SchLabelledPetriNet SchLabeledSet begin
  S => S
  T => @product (s1::S; s2::S)
  (I, O) => @cases begin
    arg1 => @product (s1::S; s2::S)
    arg2 => @product (s1::S; s2::S)
  end
  (is, os) => begin
    arg1 => s1
    arg2 => s2
  end
  (it, ot) => begin
    arg1 => (s1 => s1; s2 => s2)
    arg2 => (s1 => s1; s2 => s2)
  end
  
  Name => Label
  sname => label
  tname => s1 ⋅ label # XXX: Should use both labels.
end;
```
1. What is the arg1/arg2 thing?
2. What would it take to fix the # XXX?
3. We need to color the transitions based on the types in a typed petri net in order to do the stratification, can we calculate the typing with this too?

**Comment by olynch** [comment]
This looks awesome! See @kris-brown, I knew we'd learn something cool by thinking about the general form of the problem you were trying to solve.

**Review by olynch — APPROVED** [review]
Because this is just a notebook, I think we should merge this; there's no point in this languishing in a PR

**Comment by epatters** [comment]
Sounds good, I leave that whoever is managing this repo.

**Pull request merged**
